name: Create PRs

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repo name'
        required: true
      prs:
        description: 'Number of PRs to open'
        required: true
      fork_from:
        description: ''
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run PowerShell script
        shell: pwsh
        run: ./create-prs.ps1
