name: Create PRs

on:
  workflow_dispatch:
    inputs:
      prs:
        description: 'Number of PRs to create'
        required: true
        default: '5'

jobs:
  generate-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Configure GitHub CLI authentication
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GitHub CLI authenticated via GH_TOKEN"

      - name: Run PowerShell script to create PRs
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./make-prs.ps1 -Count ${{ github.event.inputs.prs }}