name: Create PRs

on:
  workflow_dispatch:
    inputs:
      prs:
        description: 'Number of PRs to create'
        required: true
        default: '5'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config --global user.email "bot@snir.dev"
          git config --global user.name "Snir Bot"

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Run PowerShell script
        shell: pwsh
        env:
        GH_TOKEN: ${{ secrets.gh-cli-pat }}
        run: ./make-prs.ps1 -Count ${{ github.event.inputs.prs }}