name: Create PRs

on:
  workflow_dispatch:
    inputs:
      prs:
        description: 'Number of PRs to create'
        required: true
        default: '5'

jobs:
  generate-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GH CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./create-prs.ps1 -RepoName "${{ github.repository }}" -PRs ${{ github.event.inputs.prs }}
